routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('', 'AntrianController@indexAntrian')->name('antrian');
Route::get('antrian/konfirmasi/{id}', 'AntrianController@konfirmasi')->name('antrian.konfirmasi');
Route::get('antrian/cetak', 'AntrianController@AntrianCetak')->name('antrian.cetak');
Route::get('antrian/desain', 'AntrianController@AntrianDesain')->name('antrian.desain');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
    Route::get('tes', function() {
    	return Hash::make('admin');
	});

	Route::get('/', 'Dashboard@cek');
	Route::get('/dashboard', 'Dashboard@index')->name('dash');

	Route::group(['prefix' => 'keuangan'], function() {
		Route::get('/utang', 'BeliController@utang')->name('utang');
		Route::get('/utang/{id}', 'BeliController@utangbeli')->name('utangbeli');
		Route::resource('/piutang', 'PiutangController');
		Route::resource('/pembelian', 'BeliController');
		Route::resource('/belidet', 'BeliController');
		Route::resource('/tmpbeli', 'TmpBeliController');
		Route::get('harga/{id}', 'TmpBeliController@show');
	});


	Route::group(['prefix' => 'laporan'], function() {
		Route::get('/pembelian', 'BeliController@laporan')->name('lapbeli');
	
		Route::group(['prefix' => 'cetak'], function() {
			Route::get('/detailbeli/{id}', 'BeliController@cetakdetail')->name('cetdetbeli');
			Route::get('/beli/{awal}&{akhir}', 'BeliController@cetak')->name('cetbeli');		
		});
	});


	Route::group(['prefix' => 'master'], function() {

		Route::resource('/tools', 'ToolsController');
		Route::group(['prefix' => 'tools'], function() {
			Route::resource('/barang', 'BarangController');
			Route::resource('/printer', 'PrinterController');
			Route::resource('/potong', 'JenisPotongController');
			Route::resource('/display', 'JenisDisplayController');
		});
	

		Route::resource('/harga', 'HargaController');
		Route::resource('/member', 'MemberController');
		Route::resource('/supplier', 'SupplierController');
		Route::resource('/costumer', 'PelangganController');
		Route::post('/costumer/storeModal', 'PelangganController@storeModal')->name('costumer.storeModal');
		Route::post('harga/merchant/', 'HargaController@merchant')->name('harga.merchant');
		Route::post('harga/outdoor/', 'HargaController@outdoor')->name('harga.outdoor');
		Route::post('harga/print-quarto/', 'HargaController@printQuarto')->name('harga.printQuarto');
		Route::post('harga/indoor/', 'HargaController@indoor')->name('harga.indoor');
		Route::post('harga/large-format/', 'HargaController@largeFormat')->name('harga.largeFormat');
		Route::post('harga/costum-produk/', 'HargaController@costumProduk')->name('harga.costumProduk');
		Route::post('harga/merchant/update/', 'HargaController@merchantEdit')->name('harga.merchantUpdate');
		Route::post('harga/outdoor/update/', 'HargaController@outdoorEdit')->name('harga.outdoorUpdate');
		Route::delete('harga/merchant/destroy/{id}', 'HargaController@merchantDestroy')->name('harga.merchantDestroy');
		Route::post('harga/large-format/update/', 'HargaController@largeFormatEdit')->name('harga.largeFormatUpdate');
		Route::post('harga/print-quarto/update/', 'HargaController@printQuartoEdit')->name('harga.printQuartoUpdate');
		Route::post('harga/indoor/update/', 'HargaController@indoorEdit')->name('harga.indoorUpdate');
		Route::post('harga/costum-produk/update/', 'HargaController@costumProdukEdit')->name('harga.costumProdukUpdate');
		Route::delete('harga/outdoor/destroy/{id}', 'HargaController@outdoorDestroy')->name('harga.outdoorDestroy');
		Route::delete('harga/large-format/destroy/{id}', 'HargaController@largeFormatDestroy')->name('harga.largeFormatDestroy');
		Route::delete('harga/indoor/destroy/{id}', 'HargaController@indoorDestroy')->name('harga.indoorDestroy');
		Route::delete('harga/print-quarto/destroy/{id}', 'HargaController@printQuartoDestroy')->name('harga.printQuartoDestroy');
		Route::delete('harga/costum-produk/destroy/{id}', 'HargaController@costumProdukDestroy')->name('harga.costumProdukDestroy');
	});

	Route::group(['prefix' => 'transaksi'], function() {
		Route::resource('antrian', 'AntrianController');
		Route::resource('order', 'OrderKerjaController');
		Route::resource('produksi', 'ProduksiController');
		Route::resource('gudang', 'GudangController');
		
		Route::group(['prefix' => 'order'], function() {

			Route::get('update_status/{id}', 'OrderKerjaController@update_status')->name('order.update_status');

			Route::group(['prefix' => 'outdoor'], function() {
				Route::get('data/{barang}/{editor}/{pelanggan}/{qty}/{p}/{l}', 'HargaOutdoorController@getData');
			});

			Route::group(['prefix' => 'indoor'], function() {
				Route::get('data/{barang}/{editor}/{pelanggan}/{qty}/{p}/{l}/{tipe}', 'HargaIndoorController@getData');
				
			});

			Route::group(['prefix' => 'merchant'], function() {
				Route::get('data/{barang}/{pelanggan}/{qty}', 'HargamerchantController@getData');
				
			});

			Route::group(['prefix' => 'print'], function() {
				Route::get('data/{barang}/{pelanggan}/{qty}/{ukuran}/{editor}/{tipe_print}/{kaki}', 'HargaPrintController@getData');
				
			});

			Route::group(['prefix' => 'costum'], function() {
				Route::get('data/{nama_produk}/{produk}/{pelanggan}/{qty}', 'HargaCostumController@getData');
				
			});

			Route::post('tambah/{id}', 'OrderKerjaController@detail')->name('order.detail');
			Route::delete('hapus/{id}', 'OrderKerjaController@destroySubKerja')->name('order.subkerja.hapus');

			Route::group(['prefix' => 'store'], function() {
				Route::post('outdoor/', 'OrderKerjaController@storeOutdoor')->name('storeOutdoor');
				Route::post('indoor/', 'OrderKerjaController@storeIndoor')->name('storeIndoor');
				Route::post('merchant/', 'OrderKerjaController@storemerchant')->name('storeMerchant');
				Route::post('print-quarto/', 'OrderKerjaController@storePrintQuarto')->name('storePrintQuarto');
				Route::post('costum-produk/', 'OrderKerjaController@storeCostumProduk')->name('storeCostumProduk');
			});
		});

		Route::group(['prefix' => 'produksi'], function() {
			Route::get('show/{id}', 'ProduksiController@detail')->name('produksi.detail');
			Route::get('update_status/{id}', 'ProduksiController@update_status')->name('produksi.update_status');
		});

		Route::group(['prefix' => 'gudang'], function() {
			Route::get('update_status/{id}', 'GudangController@update_status')->name('gudang.update_status');
		});
		
	});

	Route::resource('/editor', 'EditorController');
	Route::resource('/pengguna', 'PenggunaController');
	Route::get('/pengguna/pass/{id}', 'PenggunaController@ganti')->name('gantiPass');


	Route::group(['prefix' => 'inventory'], function() {
		Route::get('pembelian/barang/{id}', 'PembelianController@getBarang');
		Route::resource('stokbarang', 'StokBarangController');
	});

});

Auth::routes();

resources/views/transaksi/order/order.blade.php
@extends('layout.layout')
@section('title', 'Pembelian')
@section('content')
	<div class="container-padding animated fadeInRight"> 
		<div class="row"> 
			<!-- Start Panel -->
			<div class="col-md-12">
				@if(Session::has('alert-success'))
					<div class="foxlabel-alert foxlabel-alert-icon alert3"> <i class="fa fa-check"></i> <a href="#" class="closed">&times;</a> {{ \Illuminate\Support\Facades\Session::get('alert-success') }}</div>
				@endif
				<div class="panel panel-default">
					<a href="{{ route('order.create') }}" class="btn btn-default"><i class="fa fa-plus-circle"></i>Tambah Data</a>
					<br>
					<br>
					<div class="panel-title"> Data Pembelian </div>
					<div class="panel-body table-responsive">
						<table id="example0" class="table display">
							<thead>
								<tr>
									<th>No.</th>
									<th>Order</th>
									<th>Pelanggan</th>
									<th>Tanggal Order</th>
									<th colspan="2">Aksi</th>
								</tr>
							</thead>
							<tbody>
								@forelse($data as $index => $datas)
								<tr>
									<td>{{ $index + 1 }}</td>
									<td>{{ $datas->order }}</td>
									<td>{{ $datas->pelanggan->nama }}</td>
									<td>{{ $datas->tanggal_ord }}</td>
									<td>
																	
										<form action="{{ route('order.destroy', $datas->id) }}" class="form-horizontal" method="post">
											{{ csrf_field() }}
											{{ method_field('DELETE') }}

										<a href="{{ route('order.show', $datas->id) }}" class="btn btn-option2"><i class="fa fa-info"></i>Detail</a>
										<button class="btn btn-danger" onclick="return confirm('Yakin ingin menghapus data ?')"><i class="fa fa-check"></i>Delete</button>
										</form>
									</td>
								</tr>
								@empty
								@endforelse
							</tbody>
							<tfoot>
								
							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- End Panel --> 
		</div>
		<!-- End Row --> 
	</div>
@endsection

resources/views/transaksi/order/order_create.blade.php
@extends('layout.layout')
@section('title', 'Tambah Data Order')
@section('content')
<script type="text/javascript" src="{{asset('js/jquery.min.js')}}"></script> 
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="widget-box">
                        
            <div class="widget-title"> Data Harga Produk <a href="#" data-toggle="modal" data-target="#tambah" class="btn btn-default"><i class="fa fa-plus-circle"></i>Tambah Costumer</a>
                    
            </div>
            <div role="tabpanel"> 
                <br>
                <!-- Nav tabs -->
                <ul class="nav nav-pills" role="tablist">
                    <li class="nav-item"><a class="btn btn-default" href="#outdoor" aria-controls="outdoor" role="tab" data-toggle="tab">Outdoor</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#indoor" aria-controls="indoor" role="tab" data-toggle="tab">Indoor</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#merchant" aria-controls="merchant" role="tab" data-toggle="tab">Merchant</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#a3" aria-controls="a3" role="tab" data-toggle="tab">Print A3</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#costum" aria-controls="costum" role="tab" data-toggle="tab">Costum</a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane" id="outdoor">
                            @include('transaksi.order.produk.outdoor')
                    </div>
                    <div role="tabpanel" class="tab-pane" id="indoor">
                            @include('transaksi.order.produk.indoor')
                    </div>
                    <div role="tabpanel" class="tab-pane" id="merchant">
                            @include('transaksi.order.produk.merchant')
                    </div>
                    <div role="tabpanel" class="tab-pane" id="a3">
                            @include('transaksi.order.produk.a3')
                    </div>
                    <div role="tabpanel" class="tab-pane" id="costum">
                            @include('transaksi.order.produk.costum')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@include('master.pelanggan.modal')
@endsection

resources/views/transaksi/order/order_detail.blade.php
@extends('layout.layout')
@section('title', 'Tambah Data Order')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title"> Total Harga
                <ul class="panel-tools">
                    <li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
                </ul> 
            </div>
            <div class="panel-body">
                <h1>Rp. {{ number_format($totalan->total) }}</h1>
            </div>
        </div>
    </div>
</div>
<div class="row"> 
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title"> Data Pekerjaan </div>
            @if($order->status_produksi < '3')
            <a href="{{ route('order.edit', $id) }}" class="btn btn-default"><i class="fa fa-plus-circle"></i>Tambah Order</a>
            @endif
               <a href="{{ route('order.index') }}" class="btn btn-default">Kembali</a>

            <br>
            <br>
            <div class="panel-body table-responsive">
                <table id="example0" class="table display">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Deadline</th>
                            <th>Produk</th>
                            <th>Bahan</th>
                            <th>Diskon</th>
                            <th>Qty</th>
                            <th>Total Harga</th>
                            <th>Keterangan</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($data as $index => $datas)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <th>{{ $datas->tgl_deadline }}</th>
                            <td>{{ $datas->nama_produk }}</td>
                            <td>{{ is_null($datas->barang_id) ? '-' : $datas->barang->nm_barang }}</td>
                            <td>{{ $datas->diskon }} %</td>
                            <td>{{ $datas->qty }}</td>
                            <td>Rp. {{ number_format($datas->total) }}</td>
                            <td>{!! $datas->keterangan !!}</td>
                        </tr>
                        @empty
                        @endforelse
                    </tbody>
                    <tfoot>

                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- End Panel --> 
</div>

@endsection

resources/views/transaksi/order/order_edit.blade.php
@extends('layout.layout')
@section('title', 'Tambah Data Order')
@section('content')
<script type="text/javascript" src="{{asset('js/jquery.min.js')}}"></script> 
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="panel panel-default">
        	<div class="panel-title"> Data Order
        		<ul class="panel-tools">
        			<li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
        			<li><a class="icon expand-tool"><i class="fa fa-expand"></i></a></li>
        		</ul> 
        	</div>
        	<div class="panel-body">
                <form method="post" action="{{ route('storeOutdoor') }}" >
                <div id="outdoor_show" class="row col-md-12">
                 <div class="col-md-12 col-lg-2">
                     <div class="form-group">
                        <label for="input2" class="form-label">No</label>
                        <input type="text" class="form-control" name="noorder" required disabled value="{{ $order->order }}">
                    </div>
                </div>

                <div class="col-md-12 col-lg-4">
                    <div class="form-group">
                        <label for="select2" class="form-label">Customer</label>
                        <input type="hidden" id="idmember" name="member_id" value="{{ $order->pelanggan->member_id }}">
                        <input type="text" class="form-control" name="customer_id" required disabled value="{{ $order->pelanggan->nama }} [{{ $order->pelanggan->member->nm_tipe }}]">
                        
                    </div>

                </div>
        
                <div class="col-md-12 col-lg-3">
                    <div class="form-group">
                        <label class="form-label">Tanggal Order</label>
                        <fieldset>
                            <div class="control-group">
                                <div class="controls">
                                    <div class="input-prepend input-group"> 
                                        <input type="text" id="date-picker" class="form-control" name="tanggal" value="{{ $order->tanggal }}" disabled required>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div> 

                
            </div>
        </form>
    
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="widget-box">
            <div class="widget-title"> Data Order Produk </div>
            <div role="tabpanel "> 
                <br>
                <!-- Nav tabs -->
                <ul class="nav nav-pills" role="tablist">
                    <li class="nav-item"><a class="btn btn-default" href="#outdoor" aria-controls="outdoor" role="tab" data-toggle="tab">Outdoor</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#indoor" aria-controls="indoor" role="tab" data-toggle="tab">Indoor</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#merchant" aria-controls="merchant" role="tab" data-toggle="tab">Merchant</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#a3" aria-controls="a3" role="tab" data-toggle="tab">Print A3</a></li>
                    <li class="nav-item"><a class="btn btn-default" href="#costum" aria-controls="costum" role="tab" data-toggle="tab">Costum</a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                        <div role="tabpanel " class="tab-pane active" id="outdoor">
                            @include('transaksi.order.produk.outdoor_edit')
                        </div>
                        <div role="tabpanel" class="tab-pane" id="indoor">
                            @include('transaksi.order.produk.indoor_edit')
                        </div>
                        <div role="tabpanel" class="tab-pane" id="merchant">
                            @include('transaksi.order.produk.merchant_edit')
                        </div>
                        <div role="tabpanel" class="tab-pane" id="a3">
                            @include('transaksi.order.produk.a3_edit')
                        </div>
                        <div role="tabpanel" class="tab-pane" id="costum">
                            @include('transaksi.order.produk.costum_edit')
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title"> Total Harga
                <ul class="panel-tools">
                    <li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
                </ul> 
            </div>
            <div class="panel-body">
                <h1>Rp. {{ number_format($totalan->total) }}
                </h1>
                <a href="{{ route('order.index') }}" class="btn btn-default">Kembali</a>
            </div>
        </div>
    </div>
</div>
<div class="row"> 
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-title"> Data Pekerjaan </div>
            <div class="panel-body table-responsive">
                <table id="example0" class="table display">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Produk</th>
                            <th>Bahan</th>
                           
                            <th>Diskon</th>
                            <th>Qty</th>
                            <th>Harga</th>
                            <th>Total Harga</th>
                            <th>Keterangan</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($data as $index => $datas)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $datas->nama_produk }}</td>
                            <td>{{ is_null($datas->barang_id) ? '-' : $datas->barang->nm_barang }}</td>
                           
                            <td>{{ $datas->diskon }} %</td>
                            <td>{{ $datas->qty }}</td>
                            <td>Rp. {{ number_format($datas->harga) }}</td>
                            <td>Rp. {{ number_format($datas->total) }}</td>
                            <td>{!! $datas->keterangan !!}</td>
                            <td>
                                <form action="{{ route('order.subkerja.hapus', $datas->id) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-danger" onclick="return confirm('Yakin ingin menghapus data ?')"><i class="fa fa-trash"></i>Delete</button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        @endforelse
                    </tbody>
                    <tfoot>

                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <!-- End Panel --> 
</div>

@endsection