routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('', 'AntrianController@indexAntrian')->name('antrian');
Route::get('antrian/konfirmasi/{id}', 'AntrianController@konfirmasi')->name('antrian.konfirmasi');
Route::get('antrian/cetak', 'AntrianController@AntrianCetak')->name('antrian.cetak');
Route::get('antrian/desain', 'AntrianController@AntrianDesain')->name('antrian.desain');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
    Route::get('tes', function() {
    	return Hash::make('admin');
	});

	Route::get('/', 'Dashboard@cek');
	Route::get('/dashboard', 'Dashboard@index')->name('dash');

	Route::group(['prefix' => 'keuangan'], function() {
		Route::get('/utang', 'BeliController@utang')->name('utang');
		Route::get('/utang/{id}', 'BeliController@utangbeli')->name('utangbeli');
		Route::resource('/piutang', 'PiutangController');
		Route::resource('/pembelian', 'BeliController');
		Route::resource('/belidet', 'BeliController');
		Route::resource('/tmpbeli', 'TmpBeliController');
		Route::get('harga/{id}', 'TmpBeliController@show');
	});


	Route::group(['prefix' => 'laporan'], function() {
		Route::get('/pembelian', 'BeliController@laporan')->name('lapbeli');
	
		Route::group(['prefix' => 'cetak'], function() {
			Route::get('/detailbeli/{id}', 'BeliController@cetakdetail')->name('cetdetbeli');
			Route::get('/beli/{awal}&{akhir}', 'BeliController@cetak')->name('cetbeli');		
		});
	});


	Route::group(['prefix' => 'master'], function() {

		Route::resource('/tools', 'ToolsController');
		Route::group(['prefix' => 'tools'], function() {
			Route::resource('/barang', 'BarangController');
			Route::resource('/printer', 'PrinterController');
			Route::resource('/potong', 'JenisPotongController');
			Route::resource('/display', 'JenisDisplayController');
		});
	

		Route::resource('/harga', 'HargaController');
		Route::resource('/member', 'MemberController');
		Route::resource('/supplier', 'SupplierController');
		Route::resource('/costumer', 'PelangganController');
		Route::post('/costumer/storeModal', 'PelangganController@storeModal')->name('costumer.storeModal');
		Route::post('harga/merchant/', 'HargaController@merchant')->name('harga.merchant');
		Route::post('harga/outdoor/', 'HargaController@outdoor')->name('harga.outdoor');
		Route::post('harga/print-quarto/', 'HargaController@printQuarto')->name('harga.printQuarto');
		Route::post('harga/indoor/', 'HargaController@indoor')->name('harga.indoor');
		Route::post('harga/large-format/', 'HargaController@largeFormat')->name('harga.largeFormat');
		Route::post('harga/costum-produk/', 'HargaController@costumProduk')->name('harga.costumProduk');
		Route::post('harga/merchant/update/', 'HargaController@merchantEdit')->name('harga.merchantUpdate');
		Route::post('harga/outdoor/update/', 'HargaController@outdoorEdit')->name('harga.outdoorUpdate');
		Route::delete('harga/merchant/destroy/{id}', 'HargaController@merchantDestroy')->name('harga.merchantDestroy');
		Route::post('harga/large-format/update/', 'HargaController@largeFormatEdit')->name('harga.largeFormatUpdate');
		Route::post('harga/print-quarto/update/', 'HargaController@printQuartoEdit')->name('harga.printQuartoUpdate');
		Route::post('harga/indoor/update/', 'HargaController@indoorEdit')->name('harga.indoorUpdate');
		Route::post('harga/costum-produk/update/', 'HargaController@costumProdukEdit')->name('harga.costumProdukUpdate');
		Route::delete('harga/outdoor/destroy/{id}', 'HargaController@outdoorDestroy')->name('harga.outdoorDestroy');
		Route::delete('harga/large-format/destroy/{id}', 'HargaController@largeFormatDestroy')->name('harga.largeFormatDestroy');
		Route::delete('harga/indoor/destroy/{id}', 'HargaController@indoorDestroy')->name('harga.indoorDestroy');
		Route::delete('harga/print-quarto/destroy/{id}', 'HargaController@printQuartoDestroy')->name('harga.printQuartoDestroy');
		Route::delete('harga/costum-produk/destroy/{id}', 'HargaController@costumProdukDestroy')->name('harga.costumProdukDestroy');
	});

	Route::group(['prefix' => 'transaksi'], function() {
		Route::resource('antrian', 'AntrianController');
		Route::resource('order', 'OrderKerjaController');
		Route::resource('produksi', 'ProduksiController');
		Route::resource('gudang', 'GudangController');
		
		Route::group(['prefix' => 'order'], function() {

			Route::get('update_status/{id}', 'OrderKerjaController@update_status')->name('order.update_status');

			Route::group(['prefix' => 'outdoor'], function() {
				Route::get('data/{barang}/{editor}/{pelanggan}/{qty}/{p}/{l}', 'HargaOutdoorController@getData');
			});

			Route::group(['prefix' => 'indoor'], function() {
				Route::get('data/{barang}/{editor}/{pelanggan}/{qty}/{p}/{l}/{tipe}', 'HargaIndoorController@getData');
				
			});

			Route::group(['prefix' => 'merchant'], function() {
				Route::get('data/{barang}/{pelanggan}/{qty}', 'HargamerchantController@getData');
				
			});

			Route::group(['prefix' => 'print'], function() {
				Route::get('data/{barang}/{pelanggan}/{qty}/{ukuran}/{editor}/{tipe_print}/{kaki}', 'HargaPrintController@getData');
				
			});

			Route::group(['prefix' => 'costum'], function() {
				Route::get('data/{nama_produk}/{produk}/{pelanggan}/{qty}', 'HargaCostumController@getData');
				
			});

			Route::post('tambah/{id}', 'OrderKerjaController@detail')->name('order.detail');
			Route::delete('hapus/{id}', 'OrderKerjaController@destroySubKerja')->name('order.subkerja.hapus');

			Route::group(['prefix' => 'store'], function() {
				Route::post('outdoor/', 'OrderKerjaController@storeOutdoor')->name('storeOutdoor');
				Route::post('indoor/', 'OrderKerjaController@storeIndoor')->name('storeIndoor');
				Route::post('merchant/', 'OrderKerjaController@storemerchant')->name('storeMerchant');
				Route::post('print-quarto/', 'OrderKerjaController@storePrintQuarto')->name('storePrintQuarto');
				Route::post('costum-produk/', 'OrderKerjaController@storeCostumProduk')->name('storeCostumProduk');
			});
		});

		Route::group(['prefix' => 'produksi'], function() {
			Route::get('show/{id}', 'ProduksiController@detail')->name('produksi.detail');
			Route::get('update_status/{id}', 'ProduksiController@update_status')->name('produksi.update_status');
		});

		Route::group(['prefix' => 'gudang'], function() {
			Route::get('update_status/{id}', 'GudangController@update_status')->name('gudang.update_status');
		});
		
	});

	Route::resource('/editor', 'EditorController');
	Route::resource('/pengguna', 'PenggunaController');
	Route::get('/pengguna/pass/{id}', 'PenggunaController@ganti')->name('gantiPass');


	Route::group(['prefix' => 'inventory'], function() {
		Route::get('pembelian/barang/{id}', 'PembelianController@getBarang');
		Route::resource('stokbarang', 'StokBarangController');
	});

});

Auth::routes();

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    protected $guarded = [];

    public static $outdoor = '1';
    public static $indoor = '2';
    public static $merchant = '3';
    public static $print_a3 = '4';
    public static $costum = '5';

    public function getTipeProdukAttribute()
    {
        $label = [
            Barang::$outdoor => 'Outdoor',
            Barang::$indoor => 'Indoor',
            Barang::$merchant => 'Merchant',
            Barang::$print_a3 => 'Print A3',
            Barang::$costum => 'Costum',
        ];
        return $label[$this->produk_id];
    }

    public function scopeTipeProduk($query, $string)
    {
        if ($string == '1') {
            return $query->where('produk_id', 1);

        } else if ($string == '2') {
            return $query->where('produk_id', 2);

        } else if ($string == '3') {
            return $query->where('produk_id', 3);

        } else if ($string == '4') {
            return $query->where('produk_id', 4);

        } else if ($string == '5') {
            return $query->where('produk_id', 5);

        }
        
    }
    public function Supplier()
    {
    	return $this->belongsTo(Supplier::class);
    }
    public function HargaOutdoor()
    {
        return $this->hasMany('HargaOutdoor');
    }
    public function TmpBeli()
    {
    	return $this->hasMany('TmpBeli');
    }
    public function HargaIndoor()
    {
    	return $this->hasMany('HargaIndoor');
    }
    public function HargaMerchant()
    {
    	return $this->hasMany('HargaMerchant');
    }
    public function HargaPrint()
    {
    	return $this->hasMany('HargaPrint');
    }
    public function HargaLarge()
    {
    	return $this->hasMany('HargaLarge');
    }
    public function OrderKerjaSub()
    {
    	return $this->hasMany('OrderKerjaSub');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use App\Models\Supplier;
use Illuminate\Http\Request;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Barang::all();
        return view('master.tools.barang.barang', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $supplier = Supplier::all();
        return view('master.tools.barang.barang_create', compact('supplier'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Barang();
        $data->supplier_id = $request->supplier_id;
        $data->barcode = $request->barcode;
        $data->produk_id = $request->produk_id;
        $data->nm_barang = $request->nm_barang;
        $data->kategori = $request->kategori;
        $data->satuan = $request->satuan;
        $data->hrg_beli = $request->hrg_beli;
        $data->min_stok = $request->min_stok;
        $data->save();
        return redirect()->route('tools.index')->with('alert-barang', 'Data Berhasil Ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Barang::where('id', $id)->get();
        $supplier = Supplier::all();
        return view('master.tools.barang.barang_edit', compact('data', 'supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Barang::where('id', $id)->first();
        $data->supplier_id = $request->supplier_id;
        $data->barcode = $request->barcode;
        $data->produk_id = $request->produk_id;
        $data->nm_barang = $request->nm_barang;
        $data->kategori = $request->kategori;
        $data->satuan = $request->satuan;
        $data->hrg_beli = $request->hrg_beli;
        $data->min_stok = $request->min_stok;
        $data->save();
        return redirect()->route('tools.index')->with('alert-barang', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Barang::where('id', $id)->delete();
        return redirect()->route('tools.index')->with('alert-barang', 'Data Berhasil Dihapus');
    }
}

app/Http/Controllers/ToolsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use App\Models\Printer;
use App\Models\JenisPotong;
use App\Models\JenisDisplay;
use Illuminate\Http\Request;

class ToolsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $barang = Barang::all();
        $printer = Printer::all();
        $potong = JenisPotong::all();
        $display = JenisDisplay::all();
        return view('master.tools.tools', compact('barang', 'printer', 'potong', 'display'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/master/tools/barang/barang.blade.php
			<!-- Start Panel -->
			<div class="col-md-12">
				@if(Session::has('alert-barang'))
					<div class="foxlabel-alert foxlabel-alert-icon alert3"> <i class="fa fa-check"></i> <a href="#" class="closed">&times;</a> {{ \Illuminate\Support\Facades\Session::get('alert-barang') }}</div>
				@endif
				<div class="panel panel-default">
					<a href="{{ route('barang.create') }}" class="btn btn-default"><i class="fa fa-plus-circle"></i>Tambah Data</a>
					<br>
					<br>
					<div class="panel-title"> Data Barang </div>
					<div class="panel-body table-responsive">
						<table id="example0" class="table display">
							<thead>
								<tr>
									<th>No.</th>
									<th>Barcode</th>
									<th>Tipe Cetak</th>
									<th>Kategori</th>
									<th>Satuan</th>
									<th>Supplier</th>
									<th>Harga Beli</th>
									<th>Min. Stok</th>
									<th>Aksi</th>
								</tr>
							</thead>
							<tbody>
								@forelse($barang as $index => $datas)
								<tr>
									<td>{{ $index + 1 }}</td>
									<td>{{ $datas->barcode }}</td>
									<td>{{ $datas->tipe_produk }}</td>
									<td>{{ $datas->kategori }}</td>
									<td>{{ $datas->satuan }}</td>
									<td>{{ $datas->supplier->nm_lengkap }}</td>
									<td>{{ $datas->hrg_beli }}</td>
									<td>{{ $datas->min_stok }}</td>
									<td>
										<form action="{{ route('barang.destroy', $datas->id) }}" method="post">
											{{ csrf_field() }}
											{{ method_field('DELETE') }}
										<a href="{{ route('barang.edit', $datas->id) }}" class="btn btn-option2"><i class="fa fa-info"></i>Edit</a>
										<button class="btn btn-danger" onclick="return confirm('Yakin ingin menghapus data ?')"><i class="fa fa-check"></i>Delete</button>
										</form>
									</td>
								</tr>
								@empty
								@endforelse
							</tbody>
							<tfoot>

							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- End Panel -->

resources/views/master/tools/barang/barang_create.blade.php
@extends('layout.layout')
@section('title', 'Tambah Barang')
@section('content')
	<div class="row">
        <div class="col-md-12">
        <div class="panel panel-default">
        	<div class="panel-title"> Tambah Data Barang
        		<ul class="panel-tools">
        			<li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
        			<li><a class="icon expand-tool"><i class="fa fa-expand"></i></a></li>
        			<li><a class="icon closed-tool"><i class="fa fa-times"></i></a></li>
        		</ul>
        	</div>
        	<div class="panel-body">
        		<form method="post" action="{{ route('barang.store') }}">
        			{!! csrf_field() !!}
        			<div class="form-group">
        				<label for="input2" class="form-label">Barcode</label>
        				<input type="text" class="form-control" name="barcode" id="input2" required>
                    </div>
                    <div class="form-group">
                        <label for="select2" class="form-label">Tipe Cetak</label>
                        <select class="form-control" name="produk_id" required>
                            <option>-- Pilih Tipe Cetak --</option>
                            <option value="1">Outdoor</option>
                            <option value="2">Indoor</option>
                            <option value="3">Merchant</option>
                            <option value="4">Print A3</option>
                            <option value="5">Costum</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="input3" class="form-label">Nama Barang</label>
                        <input type="text" class="form-control" name="nm_barang" id="input3" required>
                    </div>
        			<div class="form-group">
        				<label for="input4" class="form-label">Kategori</label>
        				<input type="text" class="form-control" name="kategori" id="input4" required>
        			</div>
                    <div class="form-group">
                        <label for="input5" class="form-label">Satuan</label>
                        <input type="text" class="form-control" name="satuan" id="input5" required>
                    </div>
                    <div class="form-group">
                        <label for="input6" class="form-label">Harga Beli</label>
                        <input type="text" class="form-control" name="hrg_beli" id="input6" value="0" required>
                    </div>
                    <div class="form-group">
                        <label for="input6" class="form-label">Minimal Stok</label>
                        <input type="text" class="form-control" name="min_stok" id="input6" value="0" required>
                    </div>
                    <div class="form-group">
                        <label for="select2" class="form-label">Supplier</label>
                        <select class="form-control" name="supplier_id" required="">
                            <option value="">-- Pilih Member --</option>
                            @foreach($supplier as $tampil)
                            <option value="{{ $tampil->id }}">{{ $tampil->nm_lengkap }}</option>
                            @endforeach
                        </select>
                    </div>
        			<button type="submit" class="btn btn-primary">Submit</button>
                    <button onclick="goBack()" class="btn btn-default">Kembali</button>
        		</form>
        	</div>
        </div>
    </div>
</div>
@endsection

resources/views/master/tools/barang/barang_edit.blade.php
@extends('layout.layout')
@section('title', 'Edit Barang')
@section('content')
	<div class="row">
        <div class="col-md-12">
        <div class="panel panel-default">
        	<div class="panel-title"> Edit Data Barang
        		<ul class="panel-tools">
        			<li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
        			<li><a class="icon expand-tool"><i class="fa fa-expand"></i></a></li>
        			<li><a class="icon closed-tool"><i class="fa fa-times"></i></a></li>
        		</ul>
        	</div>
        	<div class="panel-body">
                @foreach($data as $tampil)
        		<form method="post" action="{{ route('barang.update', $tampil->id) }}">
        			{!! csrf_field() !!}
                    {{ method_field('PUT') }}
        			<div class="form-group">
        				<label for="input2" class="form-label">Barcode</label>
        				<input type="text" class="form-control" name="barcode" id="input2" value="{{ $tampil->barcode }}" required>
                    </div>
                    <div class="form-group">
                        <label for="select2" class="form-label">Tipe Cetak</label>
                        <select class="form-control" name="produk_id" required>
                            <option>-- Pilih Tipe Cetak --</option>
                            <option value="1" {{ $tampil->produk_id == 1 ? "selected" : "" }}>Outdoor</option>
                            <option value="2" {{ $tampil->produk_id == 2 ? "selected" : "" }}>Indoor</option>
                            <option value="3" {{ $tampil->produk_id == 3 ? "selected" : "" }}>Merchant</option>
                            <option value="4" {{ $tampil->produk_id == 4 ? "selected" : "" }}>Print A3</option>
                            <option value="5" {{ $tampil->produk_id == 5 ? "selected" : "" }}>Costum</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="input3" class="form-label">Nama Barang</label>
                        <input type="text" class="form-control" name="nm_barang" id="input3" value="{{ $tampil->nm_barang }}" required>
                    </div>
        			<div class="form-group">
        				<label for="input4" class="form-label">Kategori</label>
        				<input type="text" class="form-control" name="kategori" id="input4" value="{{ $tampil->kategori }}" required>
        			</div>
                    <div class="form-group">
                        <label for="input5" class="form-label">Satuan</label>
                        <input type="text" class="form-control" name="satuan" id="input5" value="{{ $tampil->satuan }}" required>
                    </div>
                    <div class="form-group">
                        <label for="input6" class="form-label">Harga Beli</label>
                        <input type="text" class="form-control" name="hrg_beli" id="input6" value="{{ $tampil->hrg_beli }}" value="0" required>
                    </div>
                    <div class="form-group">
                        <label for="input6" class="form-label">Minimal Stok</label>
                        <input type="text" class="form-control" name="min_stok" id="input6" value="{{ $tampil->min_stok }}" value="0" required>
                    </div>
                    <div class="form-group">
                        <label for="select2" class="form-label">Supplier</label>
                        <select class="form-control" name="supplier_id" required="">
                            <option value="">-- Pilih Member --</option>
                            @foreach($supplier as $tampil2)
                            @if($tampil2->id == $tampil->supplier_id)
                            <option value="{{ $tampil2->id }}" selected>{{ $tampil2->nm_lengkap }}</option>
                            @else
                            <option value="{{ $tampil2->id }}">{{ $tampil2->nm_lengkap }}</option>
                            @endif
                            @endforeach
                        </select>
                    </div>
        			<button type="submit" class="btn btn-primary">Submit</button>
                    <button onclick="goBack()" class="btn btn-default">Kembali</button>
        		</form>
                @endforeach
        	</div>
        </div>
    </div>
</div>
@endsection