routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('', 'AntrianController@indexAntrian')->name('antrian');
Route::get('antrian/konfirmasi/{id}', 'AntrianController@konfirmasi')->name('antrian.konfirmasi');
Route::get('antrian/cetak', 'AntrianController@AntrianCetak')->name('antrian.cetak');
Route::get('antrian/desain', 'AntrianController@AntrianDesain')->name('antrian.desain');

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function() {
    Route::get('tes', function() {
    	return Hash::make('admin');
	});

	Route::get('/', 'Dashboard@cek');
	Route::get('/dashboard', 'Dashboard@index')->name('dash');

	Route::group(['prefix' => 'keuangan'], function() {
		Route::get('/utang', 'BeliController@utang')->name('utang');
		Route::get('/utang/{id}', 'BeliController@utangbeli')->name('utangbeli');
		Route::resource('/piutang', 'PiutangController');
		Route::resource('/pembelian', 'BeliController');
		Route::resource('/belidet', 'BeliController');
		Route::resource('/tmpbeli', 'TmpBeliController');
		Route::get('harga/{id}', 'TmpBeliController@show');
	});


	Route::group(['prefix' => 'laporan'], function() {
		Route::get('/pembelian', 'BeliController@laporan')->name('lapbeli');
	
		Route::group(['prefix' => 'cetak'], function() {
			Route::get('/detailbeli/{id}', 'BeliController@cetakdetail')->name('cetdetbeli');
			Route::get('/beli/{awal}&{akhir}', 'BeliController@cetak')->name('cetbeli');		
		});
	});


	Route::group(['prefix' => 'master'], function() {

		Route::resource('/tools', 'ToolsController');
		Route::group(['prefix' => 'tools'], function() {
			Route::resource('/barang', 'BarangController');
			Route::resource('/printer', 'PrinterController');
			Route::resource('/potong', 'JenisPotongController');
			Route::resource('/display', 'JenisDisplayController');
		});
	

		Route::resource('/harga', 'HargaController');
		Route::resource('/member', 'MemberController');
		Route::resource('/supplier', 'SupplierController');
		Route::resource('/costumer', 'PelangganController');
		Route::post('/costumer/storeModal', 'PelangganController@storeModal')->name('costumer.storeModal');
		Route::post('harga/merchant/', 'HargaController@merchant')->name('harga.merchant');
		Route::post('harga/outdoor/', 'HargaController@outdoor')->name('harga.outdoor');
		Route::post('harga/print-quarto/', 'HargaController@printQuarto')->name('harga.printQuarto');
		Route::post('harga/indoor/', 'HargaController@indoor')->name('harga.indoor');
		Route::post('harga/large-format/', 'HargaController@largeFormat')->name('harga.largeFormat');
		Route::post('harga/costum-produk/', 'HargaController@costumProduk')->name('harga.costumProduk');
		Route::post('harga/merchant/update/', 'HargaController@merchantEdit')->name('harga.merchantUpdate');
		Route::post('harga/outdoor/update/', 'HargaController@outdoorEdit')->name('harga.outdoorUpdate');
		Route::delete('harga/merchant/destroy/{id}', 'HargaController@merchantDestroy')->name('harga.merchantDestroy');
		Route::post('harga/large-format/update/', 'HargaController@largeFormatEdit')->name('harga.largeFormatUpdate');
		Route::post('harga/print-quarto/update/', 'HargaController@printQuartoEdit')->name('harga.printQuartoUpdate');
		Route::post('harga/indoor/update/', 'HargaController@indoorEdit')->name('harga.indoorUpdate');
		Route::post('harga/costum-produk/update/', 'HargaController@costumProdukEdit')->name('harga.costumProdukUpdate');
		Route::delete('harga/outdoor/destroy/{id}', 'HargaController@outdoorDestroy')->name('harga.outdoorDestroy');
		Route::delete('harga/large-format/destroy/{id}', 'HargaController@largeFormatDestroy')->name('harga.largeFormatDestroy');
		Route::delete('harga/indoor/destroy/{id}', 'HargaController@indoorDestroy')->name('harga.indoorDestroy');
		Route::delete('harga/print-quarto/destroy/{id}', 'HargaController@printQuartoDestroy')->name('harga.printQuartoDestroy');
		Route::delete('harga/costum-produk/destroy/{id}', 'HargaController@costumProdukDestroy')->name('harga.costumProdukDestroy');
	});

	Route::group(['prefix' => 'transaksi'], function() {
		Route::resource('antrian', 'AntrianController');
		Route::resource('order', 'OrderKerjaController');
		Route::resource('produksi', 'ProduksiController');
		Route::resource('gudang', 'GudangController');
		
		Route::group(['prefix' => 'order'], function() {

			Route::get('update_status/{id}', 'OrderKerjaController@update_status')->name('order.update_status');

			Route::group(['prefix' => 'outdoor'], function() {
				Route::get('data/{barang}/{editor}/{pelanggan}/{qty}/{p}/{l}', 'HargaOutdoorController@getData');
			});

			Route::group(['prefix' => 'indoor'], function() {
				Route::get('data/{barang}/{editor}/{pelanggan}/{qty}/{p}/{l}/{tipe}', 'HargaIndoorController@getData');
				
			});

			Route::group(['prefix' => 'merchant'], function() {
				Route::get('data/{barang}/{pelanggan}/{qty}', 'HargamerchantController@getData');
				
			});

			Route::group(['prefix' => 'print'], function() {
				Route::get('data/{barang}/{pelanggan}/{qty}/{ukuran}/{editor}/{tipe_print}/{kaki}', 'HargaPrintController@getData');
				
			});

			Route::group(['prefix' => 'costum'], function() {
				Route::get('data/{nama_produk}/{produk}/{pelanggan}/{qty}', 'HargaCostumController@getData');
				
			});

			Route::post('tambah/{id}', 'OrderKerjaController@detail')->name('order.detail');
			Route::delete('hapus/{id}', 'OrderKerjaController@destroySubKerja')->name('order.subkerja.hapus');

			Route::group(['prefix' => 'store'], function() {
				Route::post('outdoor/', 'OrderKerjaController@storeOutdoor')->name('storeOutdoor');
				Route::post('indoor/', 'OrderKerjaController@storeIndoor')->name('storeIndoor');
				Route::post('merchant/', 'OrderKerjaController@storemerchant')->name('storeMerchant');
				Route::post('print-quarto/', 'OrderKerjaController@storePrintQuarto')->name('storePrintQuarto');
				Route::post('costum-produk/', 'OrderKerjaController@storeCostumProduk')->name('storeCostumProduk');
			});
		});

		Route::group(['prefix' => 'produksi'], function() {
			Route::get('show/{id}', 'ProduksiController@detail')->name('produksi.detail');
			Route::get('update_status/{id}', 'ProduksiController@update_status')->name('produksi.update_status');
		});

		Route::group(['prefix' => 'gudang'], function() {
			Route::get('update_status/{id}', 'GudangController@update_status')->name('gudang.update_status');
		});
		
	});

	Route::resource('/editor', 'EditorController');
	Route::resource('/pengguna', 'PenggunaController');
	Route::get('/pengguna/pass/{id}', 'PenggunaController@ganti')->name('gantiPass');


	Route::group(['prefix' => 'inventory'], function() {
		Route::get('pembelian/barang/{id}', 'PembelianController@getBarang');
		Route::resource('stokbarang', 'StokBarangController');
	});

});

Auth::routes();

app/Models/Member.php
<?php

namespace App\Models;

use App\Models\Harga;
use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $guarded = [];

    public function Pelanggan()
    {
    	return $this->hasMany('Pelanggan');
    }
    public function Harga()
    {
    	return $this->hasMany('Harga');
    }
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Models\Member;
use Illuminate\Http\Request;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Member::all();
        return view('master.member.member', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('master.member.member_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Member();
        $data->nm_tipe = $request->nm_tipe;
        $data->keterangan = $request->keterangan;
        $data->save();
        return redirect()->route('member.index')->with('alert-success', 'Data Berhasil Ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Member::where('id', $id)->get();
        return view('master.member.member_edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Member::where('id', $id)->first();
        $data->nm_tipe = $request->nm_tipe;
        $data->keterangan = $request->keterangan;
        $data->save();
        return redirect()->route('member.index')->with('alert-success', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Member::where('id', $id)->delete();
        return redirect()->route('member.index')->with('alert-success', 'Data Berhasil Dihapus');
    }
}

resources/views/master/member/member.blade.php
@extends('layout.layout')
@section('title', 'Data Member')
@section('content')
	<div class="container-padding animated fadeInRight"> 
		<div class="row"> 
			<!-- Start Panel -->
			<div class="col-md-12">
				@if(Session::has('alert-success'))
					<div class="foxlabel-alert foxlabel-alert-icon alert3"> <i class="fa fa-check"></i> <a href="#" class="closed">&times;</a> {{ \Illuminate\Support\Facades\Session::get('alert-success') }}</div>
				@endif
				<div class="panel panel-default">
					<a href="{{ route('member.create') }}" class="btn btn-default"><i class="fa fa-plus-circle"></i>Tambah Data</a>
					<br>
					<br>
					<div class="panel-title"> Data Tipe Member </div>
					<div class="panel-body table-responsive">
						<table id="example0" class="table display">
							<thead>
								<tr>
									<th>No</th>
									<th>Tipe Member</th>
									<th>Keterangan</th>
									<th>Aksi</th>
								</tr>
							</thead>
							<tbody>
								@forelse($data as $index => $datas)
								<tr>
									<td>{{ $index + 1 }}</td>
									<td>{{ $datas->nm_tipe }}</td>
									<td>{{ $datas->keterangan }}</td>
									<td>
										<form action="{{ route('member.destroy', $datas->id) }}" method="post">
											{{ csrf_field() }}
											{{ method_field('DELETE') }}
										<a href="{{ route('member.edit', $datas->id) }}" class="btn btn-option2"><i class="fa fa-info"></i>Edit</a>
										<button class="btn btn-danger" onclick="return confirm('Yakin ingin menghapus data ?')"><i class="fa fa-check"></i>Delete</button>
										</form>
									</td>
								</tr>
								@empty
								@endforelse
							</tbody>
							<tfoot>

							</tfoot>
						</table>
					</div>
				</div>
			</div>
			<!-- End Panel --> 
		</div>
		<!-- End Row --> 
	</div>
@endsection

resources/views/master/member/member_create.blade.php
@extends('layout.layout')
@section('title', 'Tambah Tipe Member')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
        	<div class="panel-title"> Tambah Data Tipe Member
        		<ul class="panel-tools">
        			<li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
        			<li><a class="icon expand-tool"><i class="fa fa-expand"></i></a></li>
        			<li><a class="icon closed-tool"><i class="fa fa-times"></i></a></li>
        		</ul>
        	</div>
        	<div class="panel-body">
        		<form method="post" action="{{ route('member.store') }}">
        			{!! csrf_field() !!}
        			<div class="form-group">
        				<label for="input1" class="form-label">Nama Tipe Member</label>
        				<input type="text" class="form-control" name="nm_tipe" id="input1" required>
        			</div>
        			<div class="form-group">
        				<label for="textarea1" class="form-label">Keterangan</label>
        				<textarea name="keterangan" class="form-control" required=""></textarea>
        			</div>
        			<button type="submit" class="btn btn-primary">Submit</button>
        			<button onclick="goBack()" class="btn btn-default">Kembali</button>
        		</form>
        	</div>
        </div>
    </div>
</div>
@endsection

resources/views/master/member/member_edit.blade.php
@extends('layout.layout')
@section('title', 'Edit Tipe Member')
@section('content')
	<div class="row">
        <div class="col-md-12">
        <div class="panel panel-default">
        	<div class="panel-title"> Edit Data Tipe Member
        		<ul class="panel-tools">
        			<li><a class="icon minimise-tool"><i class="fa fa-minus"></i></a></li>
        			<li><a class="icon expand-tool"><i class="fa fa-expand"></i></a></li>
        			<li><a class="icon closed-tool"><i class="fa fa-times"></i></a></li>
        		</ul>
        	</div>
        	<div class="panel-body">
                @foreach($data as $tampil)
        		<form method="post" action="{{ route('member.update', $tampil->id) }}">
        			{!! csrf_field() !!}
                    {{ method_field('PUT') }}
        			<div class="form-group">
        				<label for="input1" class="form-label">Nama Tipe Member</label>
        				<input type="text" class="form-control" name="nm_tipe" id="input1" value="{{ $tampil->nm_tipe }}" required>
        			</div>
        			<div class="form-group">
        				<label for="textarea1" class="form-label">Keterangan</label>
        				<textarea name="keterangan" class="form-control" required="">{{ $tampil->keterangan }}</textarea>
        			</div>
                    @endforeach
        			<button type="submit" class="btn btn-primary">Submit</button>
        			<button onclick="goBack()" class="btn btn-default">Kembali</button>
        		</form>
        	</div>
        </div>
    </div>
</div>
@endsection